### ISSUE TITLE
Enter the group members times

### ISSUE THREAD

**Issue by Samuelhertzberg** [apeinot/java#102]
We need to enter the team members times in the time table

**Comment by Samuelhertzberg** [comment]
@Jonagoo Fill in your time one branch issue102 in the report

**Comment by Jonagoo** [comment]
Done.

**Comment by Samuelhertzberg** [comment]
That's only 20 hours tho @Jonagoo The others have 25-30.

**Comment by Samuelhertzberg** [comment]
Make a PR when you're done :)
