### ISSUE TITLE
Manually counting cyclomatic complexity of Parsed::parse() in OmitValue.java

### ISSUE THREAD

**Issue by emilelm96** [apeinot/java#4]
We will manually compute the cyclomatic complexity of _**Parsed::parse(Type, String)**_ in **_./src/main/java/com/jsoniter/spi/OmitValue.java_**. The two assignees will report their results in the report.

**Comment by Jonagoo** [comment]
I got 3.

**Comment by Jonagoo** [comment]
Going by the TA's instructions I got 21.

**Comment by apeinot** [comment]
Get also 21
