### ISSUE TITLE
Manually counting the cyclomatic complexity of IterImplSkip::skip() in IterImplSkip.java

### ISSUE THREAD

**Issue by emilelm96** [apeinot/java#5]
We will manually compute the cyclomatic complexity of _**IterImplSkip::skip(JsonIterator)**_ in **_./src/main/java/com/jsoniter/IterImplSkip.java_**. The two assignees will report their results in the report.

**Comment by Samuelhertzberg** [comment]
I manually counted and my results for the cyclomatic complexity is: *18*.
What did you get @francislaus?

**Comment by francislaus** [comment]
> I manually counted and my results for the cyclomatic complexity is: _18_.
> What did you get @francislaus?

In some way, I got 12

**Comment by Samuelhertzberg** [comment]
> > I manually counted and my results for the cyclomatic complexity is: _18_.
> > What did you get @francislaus?
> 
> In some way, I got 12

Ok so me and Lizard got 18 which is simply the number of decisions.
However the lecture slides states that the CC is the number of decisions minus exit points plus two.
This equates to 18 - 7 + 2 = 13.
We are going to need a third person on this.

**Comment by francislaus** [comment]
> > > I manually counted and my results for the cyclomatic complexity is: _18_.
> > > What did you get @francislaus?
> > 
> > 
> > In some way, I got 12
> 
> Ok so me and Lizard got 18 which is simply the number of decisions.
> However the lecture slides states that the CC is the number of decisions minus exit points plus two.
> This equates to 18 - 7 + 2 = 13.
> We are going to need a third person on this.

After re-calculating, I agree

**Comment by Samuelhertzberg** [comment]
Entering 18 as per TA:s instructions.
We should only count the number of decisisions.

**Comment by francislaus** [comment]
> Entering 18 as per TA:s instructions.
> We should only count the number of decisions.

'number_of_decision + 1' is the new formula. I agree with you on 19
