### ISSUE TITLE
Add refactoring description for readStringSlowPath in IterImplForStreaming.java

### ISSUE THREAD

**Issue by Jonagoo** [apeinot/java#68]
Describe how the function readStringSlowPath could be refactored in order to reduce complexity.

**Comment by apeinot** [comment]
Maybe you should better deal with readNumber as I have already explain IterImpl::readStringSlowPath which is quite similar

**Comment by Jonagoo** [comment]
Alright, I'll close this issue then.

**Comment by Jonagoo** [comment]
Reopening this issue in case we were supposed to refactor all 10 complex functions.
