### ISSUE TITLE
Manually counting the cyclomatic complexity of IterImplForStreaming::readNumber() in IterImplForStreaming.java

### ISSUE THREAD

**Issue by emilelm96** [apeinot/java#7]
We will manually compute the cyclomatic complexity of _**IterImplForStreaming::readNumber(JsonIterator)**_ in **_./src/main/java/com/jsoniter/spi/OmitValue.java_**. The two assignees will report their results in the report.

**Comment by emilelm96** [comment]
I got the manual cyclomatic complexity: 20. What did you get @francislaus?

**Comment by francislaus** [comment]
> I got the manual cyclomatic complexity: 20. What did you get @francislaus?

I got the same result

**Comment by emilelm96** [comment]
21 because of the default cyclomatic complexity 1 requirement.

**Comment by francislaus** [comment]
> 21 because of the default cyclomatic complexity 1 requirement.

I got the same result
