### ISSUE TITLE
Manually counting cyclomatic complexity of Config::updateBindings() in Config.java

### ISSUE THREAD

**Issue by francislaus** [apeinot/java#8]
We will manually compute the cyclomatic complexity of _**Config::updateBindings(ClassDescriptor)**_ in **_./src/main/java/com/jsoniter/spi/Config.java_**. The two assignees will report their results in the report.

**Comment by Jonagoo** [comment]
I got the complexity to 18.

**Comment by Jonagoo** [comment]
Got the same result with the new instructions.

**Comment by apeinot** [comment]
Got 18 also
