### ISSUE TITLE
Manually counting the cyclomatic complexity of CodegenImplNative::genReadOp() in CodegenImplNative.java

### ISSUE THREAD

**Issue by emilelm96** [apeinot/java#9]
We will manually compute the cyclomatic complexity of _**CodegenImplNative::genReadOp(String, Type)**_ in **_./src/main/java/com/jsoniter/CodegenImplNative.java_**. The two assignees will report their results in the report.

**Comment by Samuelhertzberg** [comment]
I have manually counted 22 decisions and 21 exit points. This should equate to a CC of 
*22 - 21 + 2 = 1 + 2 =  3*. What did you get @emilelmarsson?

**Comment by emilelm96** [comment]
I get 22 decisions and 21 exit points too, equating to 3 with the formula from the slides.

**Comment by Samuelhertzberg** [comment]
Enter 22 as per TA:s instructions.
We should only count the number of decisions.

**Comment by emilelm96** [comment]
We need to add 1, since the default cyclomatic complexity without any decisions is one, so we'll actually get 23.
